Getprocess
Medusa-Team/linux-medusa pull request #45
Opened 2022-02-28 16:43 UTC by matusjokay

2022-02-28 17:20 UTC, Programator2 requested changes
Add parent to `MED_DECIDE`.

2022-02-28 17:20 UTC, Programator2 commented on security/medusa/l2/evtype_getprocess.c
> +			  task_security(current)->validation_depth_nesting);
indentation

2022-02-28 17:20 UTC, Programator2 commented on security/medusa/l2/evtype_getprocess.c
> +			  task_security(current)->validation_depth_nesting);
never mind

2022-02-28 17:20 UTC, Programator2 commented on security/medusa/l2/evtype_getprocess.c
>  	retval = MED_DECIDE(getprocess_event, &event, &proc, &proc);
Missing parent in `MED_DECIDE`

2022-03-01 13:14 UTC, matusjokay commented
Resolved parent in MED_DECIDE

2022-03-02 10:39 UTC, Programator2 approved these changes

2022-03-02 10:39 UTC, merged